### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by MrMissx** [keselekpermen69/UserButt#12]
- [ ]  Upload video(.mp4) as streamable by default (need thumnail)
- [ ] Fix qr sticker .decode crash
- [ ] Fix unapproved message formatting derp
- [x] Fix crash when replied / mentioned by Anonymous admin on group

**Comment by KenHV** [comment]
Hey! Are there any remaining crashes from anonymous admins mentioning the user?
https://github.com/keselekpermen69/UserButt/commit/1418ebdfd340484d0fdb4063a17b98a847288328
https://github.com/keselekpermen69/UserButt/commit/46a239dd3a32e0ef86093f5f01426020be17918b
Are there any crashes apart from the ones that these commits cover?

**Comment by MrMissx** [comment]
> Hey! Are there any remaining crashes from anonymous admins mentioning the user?
> [1418ebd](https://github.com/keselekpermen69/UserButt/commit/1418ebdfd340484d0fdb4063a17b98a847288328)
> [46a239d](https://github.com/keselekpermen69/UserButt/commit/46a239dd3a32e0ef86093f5f01426020be17918b)
> Are there any crashes apart from the ones that these commits cover?

Thank you for the notice.

There is 1 left(*that i check) that when user come back from afk.
https://github.com/keselekpermen69/UserButt/blob/6643d06d044b6cbaf5c0a0828df25a7b324d8b4d/userbot/modules/afk.py#L113 
raise TypeError since `i(from USERS)` is None if the user was mentioned by Anonymous admin(s).

everything else seems working fine.


edit: myb in the future i'll just make it completely  ignore the Anonymous admin.

**Comment by KenHV** [comment]
I see, didn't notice that one. Thanks!
